const TEAM_NAME_ZH_BY_NAME: Record<string, string> = {
  afghanistan: '阿富汗',
  albania: '阿尔巴尼亚',
  algeria: '阿尔及利亚',
  andorra: '安道尔',
  angola: '安哥拉',
  argentina: '阿根廷',
  armenia: '亚美尼亚',
  aruba: '阿鲁巴',
  australia: '澳大利亚',
  austria: '奥地利',
  azerbaijan: '阿塞拜疆',
  bahamas: '巴哈马',
  bahrain: '巴林',
  bangladesh: '孟加拉国',
  barbados: '巴巴多斯',
  belarus: '白俄罗斯',
  belgium: '比利时',
  belize: '伯利兹',
  benin: '贝宁',
  bermuda: '百慕大',
  bhutan: '不丹',
  bolivia: '玻利维亚',
  'bosnia herzegovina': '波黑',
  'bosnia and herzegovina': '波黑',
  botswana: '博茨瓦纳',
  brazil: '巴西',
  bulgaria: '保加利亚',
  'burkina faso': '布基纳法索',
  burundi: '布隆迪',
  cambodia: '柬埔寨',
  cameroon: '喀麦隆',
  canada: '加拿大',
  'cape verde': '佛得角',
  'cape verde islands': '佛得角',
  'central african republic': '中非',
  chad: '乍得',
  chile: '智利',
  china: '中国',
  colombia: '哥伦比亚',
  comoros: '科摩罗',
  congo: '刚果',
  'congo dr': '刚果（金）',
  'congo democratic republic': '刚果（金）',
  'dr congo': '刚果（金）',
  'costa rica': '哥斯达黎加',
  'cote divoire': '科特迪瓦',
  'ivory coast': '科特迪瓦',
  croatia: '克罗地亚',
  cuba: '古巴',
  curacao: '库拉索',
  cyprus: '塞浦路斯',
  czechia: '捷克',
  'czech republic': '捷克',
  denmark: '丹麦',
  djibouti: '吉布提',
  dominica: '多米尼克',
  'dominican republic': '多米尼加',
  ecuador: '厄瓜多尔',
  egypt: '埃及',
  'el salvador': '萨尔瓦多',
  england: '英格兰',
  'equatorial guinea': '赤道几内亚',
  eritrea: '厄立特里亚',
  estonia: '爱沙尼亚',
  eswatini: '斯威士兰',
  ethiopia: '埃塞俄比亚',
  'faroe islands': '法罗群岛',
  fiji: '斐济',
  finland: '芬兰',
  france: '法国',
  gabon: '加蓬',
  gambia: '冈比亚',
  georgia: '格鲁吉亚',
  germany: '德国',
  ghana: '加纳',
  gibraltar: '直布罗陀',
  greece: '希腊',
  grenada: '格林纳达',
  guatemala: '危地马拉',
  guinea: '几内亚',
  'guinea bissau': '几内亚比绍',
  guyana: '圭亚那',
  haiti: '海地',
  honduras: '洪都拉斯',
  'hong kong': '中国香港',
  hungary: '匈牙利',
  iceland: '冰岛',
  india: '印度',
  indonesia: '印度尼西亚',
  iran: '伊朗',
  'ir iran': '伊朗',
  iraq: '伊拉克',
  ireland: '爱尔兰',
  israel: '以色列',
  italy: '意大利',
  jamaica: '牙买加',
  japan: '日本',
  jordan: '约旦',
  kazakhstan: '哈萨克斯坦',
  kenya: '肯尼亚',
  kosovo: '科索沃',
  kuwait: '科威特',
  kyrgyzstan: '吉尔吉斯斯坦',
  laos: '老挝',
  latvia: '拉脱维亚',
  lebanon: '黎巴嫩',
  lesotho: '莱索托',
  liberia: '利比里亚',
  libya: '利比亚',
  liechtenstein: '列支敦士登',
  lithuania: '立陶宛',
  luxembourg: '卢森堡',
  macau: '中国澳门',
  madagascar: '马达加斯加',
  malawi: '马拉维',
  malaysia: '马来西亚',
  maldives: '马尔代夫',
  mali: '马里',
  malta: '马耳他',
  mauritania: '毛里塔尼亚',
  mauritius: '毛里求斯',
  mexico: '墨西哥',
  moldova: '摩尔多瓦',
  mongolia: '蒙古',
  montenegro: '黑山',
  morocco: '摩洛哥',
  mozambique: '莫桑比克',
  myanmar: '缅甸',
  namibia: '纳米比亚',
  nepal: '尼泊尔',
  netherlands: '荷兰',
  'new caledonia': '新喀里多尼亚',
  'new zealand': '新西兰',
  nicaragua: '尼加拉瓜',
  niger: '尼日尔',
  nigeria: '尼日利亚',
  'north korea': '朝鲜',
  'korea dpr': '朝鲜',
  'north macedonia': '北马其顿',
  'northern ireland': '北爱尔兰',
  norway: '挪威',
  oman: '阿曼',
  pakistan: '巴基斯坦',
  palestine: '巴勒斯坦',
  panama: '巴拿马',
  paraguay: '巴拉圭',
  peru: '秘鲁',
  philippines: '菲律宾',
  poland: '波兰',
  portugal: '葡萄牙',
  'puerto rico': '波多黎各',
  qatar: '卡塔尔',
  romania: '罗马尼亚',
  russia: '俄罗斯',
  rwanda: '卢旺达',
  'saint kitts and nevis': '圣基茨和尼维斯',
  'saint lucia': '圣卢西亚',
  'saint vincent and the grenadines': '圣文森特和格林纳丁斯',
  samoa: '萨摩亚',
  'san marino': '圣马力诺',
  'sao tome and principe': '圣多美和普林西比',
  'saudi arabia': '沙特阿拉伯',
  scotland: '苏格兰',
  senegal: '塞内加尔',
  serbia: '塞尔维亚',
  seychelles: '塞舌尔',
  'sierra leone': '塞拉利昂',
  singapore: '新加坡',
  slovakia: '斯洛伐克',
  slovenia: '斯洛文尼亚',
  somalia: '索马里',
  'south africa': '南非',
  'south korea': '韩国',
  'korea republic': '韩国',
  spain: '西班牙',
  'sri lanka': '斯里兰卡',
  sudan: '苏丹',
  suriname: '苏里南',
  sweden: '瑞典',
  switzerland: '瑞士',
  syria: '叙利亚',
  tahiti: '塔希提',
  taiwan: '中国台北',
  tajikistan: '塔吉克斯坦',
  tanzania: '坦桑尼亚',
  thailand: '泰国',
  togo: '多哥',
  tonga: '汤加',
  'trinidad and tobago': '特立尼达和多巴哥',
  tunisia: '突尼斯',
  turkey: '土耳其',
  turkiye: '土耳其',
  turkmenistan: '土库曼斯坦',
  uganda: '乌干达',
  ukraine: '乌克兰',
  'united arab emirates': '阿联酋',
  'united states': '美国',
  usa: '美国',
  uruguay: '乌拉圭',
  uzbekistan: '乌兹别克斯坦',
  vanuatu: '瓦努阿图',
  venezuela: '委内瑞拉',
  vietnam: '越南',
  wales: '威尔士',
  yemen: '也门',
  zambia: '赞比亚',
  zimbabwe: '津巴布韦'
};

const TEAM_NAME_ZH_BY_CODE: Record<string, string> = {
  ALG: '阿尔及利亚',
  ARG: '阿根廷',
  AUS: '澳大利亚',
  AUT: '奥地利',
  BIH: '波黑',
  BRA: '巴西',
  CAN: '加拿大',
  CIV: '科特迪瓦',
  CMR: '喀麦隆',
  COD: '刚果（金）',
  COL: '哥伦比亚',
  CRC: '哥斯达黎加',
  CRO: '克罗地亚',
  CZE: '捷克',
  DEN: '丹麦',
  ECU: '厄瓜多尔',
  EGY: '埃及',
  ENG: '英格兰',
  ESP: '西班牙',
  FRA: '法国',
  GER: '德国',
  GHA: '加纳',
  HAI: '海地',
  IRN: '伊朗',
  IRQ: '伊拉克',
  JOR: '约旦',
  JPN: '日本',
  KOR: '韩国',
  MAR: '摩洛哥',
  MEX: '墨西哥',
  NED: '荷兰',
  NOR: '挪威',
  PAN: '巴拿马',
  PAR: '巴拉圭',
  POR: '葡萄牙',
  QAT: '卡塔尔',
  KSA: '沙特阿拉伯',
  SCO: '苏格兰',
  SEN: '塞内加尔',
  SUI: '瑞士',
  TUR: '土耳其',
  URU: '乌拉圭',
  USA: '美国',
  UZB: '乌兹别克斯坦',
  WAL: '威尔士'
};

export function formatTeamNameZh(name: string, code?: string): string {
  const byCode = code ? TEAM_NAME_ZH_BY_CODE[code.trim().toUpperCase()] : '';
  if (byCode) return byCode;

  const normalizedName = normalizeTeamNameKey(name);
  return TEAM_NAME_ZH_BY_NAME[normalizedName] ?? name;
}

export function teamNameSearchValues(name: string, code?: string): string[] {
  const translated = formatTeamNameZh(name, code);
  return translated && translated !== name ? [name, translated] : [name];
}

function normalizeTeamNameKey(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, ' and ')
    .replace(/[.'’]/g, '')
    .replace(/[-_/]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}
